### ISSUE TITLE
pdb name is overloaded and likely to cause confusion

### ISSUE THREAD

**Issue by matthewfischer** [raags/passdb#2]
pdb generally refers to the python debugger (https://docs.python.org/2/library/pdb.html). I think that maybe causing this pdb will cause confusion where people end up installing your module and then having issues like "unable to find set_trace()". I would suggest renaming it to something else, pwdb perhaps?

**Comment by raags** [comment]
Yeah, I infact faced the same. Renamed to passdb : https://pypi.python.org/pypi/passdb
